//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace congcong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cc_AD
    {
        public string contentText { get; set; }
        public byte[] contentImage { get; set; }
        public string contentURL { get; set; }
        public int id { get; set; }
    }
}
