//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace congcong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cc_news
    {
        public cc_news()
        {
            this.cc_admin = new HashSet<cc_admin>();
            this.cc_comment = new HashSet<cc_comment>();
        }
    
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public string position { get; set; }
        public string client { get; set; }
        public bool isAnonymous { get; set; }
        public string contentText { get; set; }
        public byte[] contentImage { get; set; }
        public int likedNum { get; set; }
        public int commentNum { get; set; }
        public string state { get; set; }
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> shareFrom { get; set; }
    
        public virtual ICollection<cc_admin> cc_admin { get; set; }
        public virtual ICollection<cc_comment> cc_comment { get; set; }
        public virtual cc_user cc_user { get; set; }
        public virtual cc_user cc_user1 { get; set; }
    }
}
