//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace congcong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cc_user
    {
        public cc_user()
        {
            this.cc_admin = new HashSet<cc_admin>();
            this.cc_comment = new HashSet<cc_comment>();
            this.cc_news = new HashSet<cc_news>();
            this.cc_news1 = new HashSet<cc_news>();
            this.cc_publicMessage = new HashSet<cc_publicMessage>();
            this.cc_publicMessage1 = new HashSet<cc_publicMessage>();
            this.cc_relationship = new HashSet<cc_relationship>();
            this.cc_relationship1 = new HashSet<cc_relationship>();
            this.cc_secretMessage = new HashSet<cc_secretMessage>();
            this.cc_secretMessage1 = new HashSet<cc_secretMessage>();
            this.cc_visiter = new HashSet<cc_visiter>();
            this.cc_visiter1 = new HashSet<cc_visiter>();
        }

     
        public string name { get; set; }
        public string email { get; set; }
        public byte[] image { get; set; }
        public string type { get; set; }
        public Nullable<int> frendsNum { get; set; }
        public Nullable<int> secretMessageNum { get; set; }
        public Nullable<int> publickMessageNum { get; set; }
        public int id { get; set; }
        public string securityQuestion { get; set; }
        public string securityAnswer { get; set; }
    
        public virtual ICollection<cc_admin> cc_admin { get; set; }
        public virtual ICollection<cc_comment> cc_comment { get; set; }
        public virtual ICollection<cc_news> cc_news { get; set; }
        public virtual ICollection<cc_news> cc_news1 { get; set; }
        public virtual ICollection<cc_publicMessage> cc_publicMessage { get; set; }
        public virtual ICollection<cc_publicMessage> cc_publicMessage1 { get; set; }
        public virtual ICollection<cc_relationship> cc_relationship { get; set; }
        public virtual ICollection<cc_relationship> cc_relationship1 { get; set; }
        public virtual ICollection<cc_secretMessage> cc_secretMessage { get; set; }
        public virtual ICollection<cc_secretMessage> cc_secretMessage1 { get; set; }
        public virtual ICollection<cc_visiter> cc_visiter { get; set; }
        public virtual ICollection<cc_visiter> cc_visiter1 { get; set; }
    }
}
