//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace congcong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class congcongEntities : DbContext
    {
        public congcongEntities()
            : base("name=congcongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cc_AD> cc_AD { get; set; }
        public DbSet<cc_admin> cc_admin { get; set; }
        public DbSet<cc_comment> cc_comment { get; set; }
        public DbSet<cc_news> cc_news { get; set; }
        public DbSet<cc_publicMessage> cc_publicMessage { get; set; }
        public DbSet<cc_relationship> cc_relationship { get; set; }
        public DbSet<cc_secretMessage> cc_secretMessage { get; set; }
        public DbSet<cc_sensitiveWord> cc_sensitiveWord { get; set; }
        public DbSet<cc_user> cc_user { get; set; }
        public DbSet<cc_visiter> cc_visiter { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
