//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace congcong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraUserInformation
    {
        public int UserId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Email { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
